services:
  postgres:
    image: postgres:17.4
    container_name: postgres-security
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts/postgres:/docker-entrypoint-initDATABASE.d/
    ports:
      - "5432:5432"
    networks:
      - security_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-security
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - postgres
    networks:
      - security_network

  redis:
    image: redis:7.4.2
    container_name: redis-security
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
      - ./init-scripts/redis/:/docker-entrypoint-initDATABASE.d/
    networks:
      - security_network

  redis_ui:
    image: patrikx3/p3x-redis-ui:latest
    container_name: redis-ui-security
    restart: always
    ports:
      - "${REDIS_UI_PORT}:7843"
    depends_on:
      - redis
    volumes:
      - ./docker-config/p3x-redis-ui:/settings
    networks:
      - security_network

volumes:
  postgres_data:
  redis_data:

networks:
  security_network:
