spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: authorizationServer
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/{DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

server:
  port: 9000

logging:
  level:
    org:
      springframework:
        security: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE

token:
  refreshToken:
    ttl: ${REFRESH_TTL:7} // 일 수 단위로