services:
  psql:
    image: postgres:15
    container_name: psql-${APP_NAME}
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./initdb.d:/docker-entrypoint-initdb.d
    networks:
      - default

  redis:
    image: redis:7
    container_name: redis-${APP_NAME}
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - default

volumes:
  postgres-data:

networks:
  default:
    name: ${APP_NAME}
